#!/bin/bash

IMAGE_NAME=$(head -1 Dockerfile | grep ^# | sed -e 's/^#//')

if [ -z "$IMAGE_NAME" ]; then
    echo "Image Name not found"
    exit 1
fi

echo -e "\e[33m+++++++++++++++++++++++++++++++++++ BUILDING DOCKER IMAGE +++++++++++++++++++++++++++++++++++++\e[0m"
docker build -t $IMAGE_NAME .
echo -e "\e[33m+++++++++++++++++++++++++++++++++++ PUSHING DOCKER IMAGE +++++++++++++++++++++++++++++++++++++\e[0m"
docker push $IMAGE_NAME